require("core.plugins_config.lualine")
require("core.plugins_config.telescope")
require("core.plugins_config.catppuccin")
require("core.plugins_config.lsp")
require("core.plugins_config.completions")
